### ISSUE TITLE
AssertionError when using example

### ISSUE THREAD

**Issue by mrpbennett** [CITGuru/PyInquirer#174]
I have tried to use the example here:

```
from __future__ import print_function, unicode_literals
from PyInquirer import prompt, print_json

questions = [
    {
        'type': 'input',
        'name': 'first_name',
        'message': 'What\'s your first name',
    }
]

answers = prompt(questions)
print_json(answers)  # use the answers as input for your app
```

But I keep getting the following error and not sure why

```
Traceback (most recent call last):
  File "/Users/paul/Developer/pycharm/pp_npi_api/app.py", line 28, in <module>
    answers = prompt(step_one)
  File "/Users/paul/.local/share/virtualenvs/pp_npi_api-yfFkFqSk/lib/python3.9/site-packages/PyInquirer/prompt.py", line 69, in prompt
    answer = run_application(
  File "/Users/paul/.local/share/virtualenvs/pp_npi_api-yfFkFqSk/lib/python3.9/site-packages/prompt_toolkit/shortcuts.py", line 576, in run_application
    output=create_output(true_color=true_color))
  File "/Users/paul/.local/share/virtualenvs/pp_npi_api-yfFkFqSk/lib/python3.9/site-packages/prompt_toolkit/shortcuts.py", line 124, in create_output
    return Vt100_Output.from_pty(
  File "/Users/paul/.local/share/virtualenvs/pp_npi_api-yfFkFqSk/lib/python3.9/site-packages/prompt_toolkit/terminal/vt100_output.py", line 424, in from_pty
    assert stdout.isatty()
AssertionError
```

**Comment by CITGuru** [comment]
;cvl;cljc
